id: opecha:P007969
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8076
  title: གཉལ་ཊཱིཀ་
  volume:
    c7c783267a9448bd9807d0fdee1cee58:
      image_group_id: I1PD96681
      title: Volume 1 of gnyal TIk
      volume_number: 1
      total_pages: 1214
  author: ''
ebook_metadata:
  title: གཉལ་ཊཱིཀ་
  author: ''
  sku: P007969
  cover: cover.jpg
  layers:
  - pagination
