id: P007969
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ8076
  title: གཉལ་ཊཱིཀ་
  author: ''
  volumes:
    c7c783267a9448bd9807d0fdee1cee58:
      image_group_id: I1PD96681
      title: Volume 1 of gnyal TIk
      volume_number: 1
      total_pages: 1214
      base_file: v001.txt
