id: P007969
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8076
  title: གཉལ་ཊཱིཀ་
  author: ''
  volumes:
    316e85b131e349babc6c6c28cb5dc90a:
      image_group_id: I1PD96681
      title: ''
      volume_number: 1
      total_pages: 1214
ebook_metadata:
  title: གཉལ་ཊཱིཀ་
  author: ''
  sku: P007969
  cover: cover.jpg
  layers:
  - pagination
